### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by jonpither** [josephwilk/hystrix-event-stream-clj#1]
Hi,

This looks cool, but I'm having trouble getting it working.

1)  (defroutes app (GET "/hystrix.stream" (hystrix-event/stream))

Where is this GET coming from? Is it Compojure? in which case it's:

```
(defroutes app (GET "/hystrix.stream" [] (hystrix-event/stream))
```

2) When I then go to open the dashboard I just get the message "loading" appear. (Took me a while to realise the host-name cannot begin with 'http').

3) I get a warning in the logs: WARN c.n.c.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.

Not sure if this is related to 2)

Anything I can do to track down what's going on?

thanks,

Jon.

**Comment by josephwilk** [comment]
Hi,

Yes I missed out the [] in the readme. Updated now to your example.

Re: 3 I see that error in working apps so I don't think thats related to the problem.

Have you tried curling the endpoint? Whats the output then?

Thanks

**Comment by nywles** [comment]
Hi Joseph,

I'm also having trouble getting this to work. Would it be possible for you to add a bare-bones netty example to the README file?

This is the app i built:

``` clojure
(ns content-distributor.handler
  (:use compojure.core)
  (:gen-class)
  (:require [compojure.handler :as handler]
            [compojure.route :as route]
            [netty.ring.adapter :refer [start-server]]
            [com.netflix.hystrix.core :refer [defcommand]]
            [hystrix-event-stream-clj.core :as hystrix-event]))

(defcommand hello
  "Safe hello!"
  []
  "Hello world!")

(defroutes app-routes
  (GET "/" [] (hello))
  (GET "/hystrix.stream" [] (hystrix-event/stream))
  (route/resources "/")
  (route/not-found "Not Found"))

(def app
  (handler/site app-routes))

(defn -main
  [port]
  (start-server app {:port (Integer. port)}))
```

The output of curl is nothing, but the running application prints:

```
Dec 13, 2013 12:56:41 PM clojure.tools.logging$eval2515$fn__2521 invoke
SEVERE: Error occurred in I/O thread
java.lang.IllegalArgumentException: No implementation of method: :write of protocol: #'netty.ring.writers/ResponseWriter found for class: lamina.core.channel.Channel
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:541)
    at netty.ring.writers$eval2193$fn__2194$G__2184__2203.invoke(writers.clj:31)
    at netty.ring.response$write_ring_response.invoke(response.clj:21)
    at netty.ring.adapter$create_handler_factory$fn__2540$fn__2545.invoke(adapter.clj:37)
    at netty.ring.adapter.proxy$org.jboss.netty.channel.SimpleChannelUpstreamHandler$0.messageReceived(Unknown Source)
    at netty.ring.adapter.proxy$org.jboss.netty.channel.SimpleChannelUpstreamHandler$0.handleUpstream(Unknown Source)
    at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

Could you give me some pointers on how to proceed?

Thanks,
Selwyn

PS. Dependencies in my project.clj are:

```
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [netty-ring-adapter "0.4.6"]
                 [compojure "1.1.6"]
                 [org.slf4j/slf4j-jdk14 "1.7.5"]
                 [com.netflix.hystrix/hystrix-clj "1.3.8"]
                 [hystrix-event-stream-clj "0.1.3"]]
```

**Comment by josephwilk** [comment]
@nywles Sure I'll take a look

**Comment by nywles** [comment]
Ok, figured it out. In order to use this event stream you need to use the Aleph http adapter that accepts channels. Here is the working sample: (perhaps you can incorporate the `require` and `start-http-server` in the README?)

``` clojure
(ns content-distributor.handler
  (:use compojure.core)
  (:gen-class)
  (:require [compojure.handler :as handler]
            [compojure.route :as route]
            [aleph.http :refer [start-http-server wrap-ring-handler]]
            [com.netflix.hystrix.core :refer [defcommand]]
            [hystrix-event-stream-clj.core :as hystrix-event]))

(defcommand hello
  "Safe hello!"
  []
  "Hello world!")

(defroutes app-routes
  (GET "/" [] (hello))
  (GET "/hystrix.stream" [] (hystrix-event/stream))
  (route/resources "/")
  (route/not-found "Not Found"))

(def app
  (handler/site app-routes))

(defn -main
  [port]
  (start-http-server (wrap-ring-handler app) {:port (Integer. port)}))
```

Thanks for your nice event stream adapter! Looking forward to using it.

**Comment by josephwilk** [comment]
Thats great, thanks @nywles. I'll add it to the readme.
